version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: just-listened-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=just_listened
    volumes:
      - postgres_data_just_listened:/var/lib/postgresql/data/

  api:
    container_name: just-listened-api
    build:
      dockerfile: deploy/dockerfile.just_listened_api
      context: .
    environment:
      - DATABASE_URL=postgresql://postgres:admin@localhost:5432/just_listened
    restart: always
    ports:
      - "8005:8000"
    networks:
      - default

volumes:
  postgres_data_just_listened:
